on:
  push:
    branches: [ main ]
env:
  RESOURCE_GROUP: rg-alicesmith

name: Azure BICEP Preview & Deploy
jobs:
  # validate-yaml:
  #   runs-on: ubuntu-latest
  #   name: Validate YAML file
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: yamllint .github/workflows/bicep.yml
    
  preview-bicep-changes:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Resource Group
      uses: Azure/cli@v1.0.6
      with:
        # Azure CLI version to be used to execute the script. If not provided, latest version is used
        # azcliversion: 2.34.1 # optional, default is agentazcliversion
        # Specify the script here
        inlineScript: |
          az version
          az group create -n $RESOURCE_GROUP -l eastus

    - name: Preview Changes fron Bicep
      uses: Azure/deployment-what-if-action@v1.0.0
      with:
        subscription: ${{ secrets.AZURE_SUBSCRIPTION }} # Subscription ID
        resourceGroup: $RESOURCE_GROUP # Resource group name
        templateFile: xr-core-server.bicep # ARM template or Bicep file
        # parametersFile: # optional # Parameters file for the ARM template or Bicep


  deploy-azure-bicep:
    needs: [preview-bicep-changes]
    runs-on: ubuntu-latest
    steps:    
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


    # Deploy Bicep to Azure
      - name: Deploy Bicep to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          #resourceGroupName: ${{ vars.AZURE_RG_ALICESMITH }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: xr-core-server.bicep
          failOnStdErr: false
          scope: resourcegroup

