on:
  push:
    branches: [ main ]

name: Azure ARM
jobs:
  # validate-yaml:
  #   runs-on: ubuntu-latest
  #   name: Validate YAML file
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: yamllint .github/workflows/bicep.yml
    
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RG_ALICESMITH }}
        template: basic-alicesmith.bicep
        scope: resourcegroup

